/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartonsCartonIdRouteImport } from './routes/cartons.$cartonId'

const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartonsCartonIdRoute = CartonsCartonIdRouteImport.update({
  id: '/cartons/$cartonId',
  path: '/cartons/$cartonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/import' | '/packing' | '/cartons/$cartonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/import' | '/packing' | '/cartons/$cartonId'
  id: '__root__' | '/' | '/import' | '/packing' | '/cartons/$cartonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  PackingRoute: typeof PackingRoute
  CartonsCartonIdRoute: typeof CartonsCartonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartons/$cartonId': {
      id: '/cartons/$cartonId'
      path: '/cartons/$cartonId'
      fullPath: '/cartons/$cartonId'
      preLoaderRoute: typeof CartonsCartonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  PackingRoute: PackingRoute,
  CartonsCartonIdRoute: CartonsCartonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
