/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as DeliveryNoteRouteImport } from './routes/delivery-note'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartonsCartonIdRouteImport } from './routes/cartons.$cartonId'

const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNoteRoute = DeliveryNoteRouteImport.update({
  id: '/delivery-note',
  path: '/delivery-note',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartonsCartonIdRoute = CartonsCartonIdRouteImport.update({
  id: '/cartons/$cartonId',
  path: '/cartons/$cartonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/packing': typeof PackingRoute
  '/cartons/$cartonId': typeof CartonsCartonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/delivery-note' | '/packing' | '/cartons/$cartonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delivery-note' | '/packing' | '/cartons/$cartonId'
  id: '__root__' | '/' | '/delivery-note' | '/packing' | '/cartons/$cartonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveryNoteRoute: typeof DeliveryNoteRoute
  PackingRoute: typeof PackingRoute
  CartonsCartonIdRoute: typeof CartonsCartonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-note': {
      id: '/delivery-note'
      path: '/delivery-note'
      fullPath: '/delivery-note'
      preLoaderRoute: typeof DeliveryNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartons/$cartonId': {
      id: '/cartons/$cartonId'
      path: '/cartons/$cartonId'
      fullPath: '/cartons/$cartonId'
      preLoaderRoute: typeof CartonsCartonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveryNoteRoute: DeliveryNoteRoute,
  PackingRoute: PackingRoute,
  CartonsCartonIdRoute: CartonsCartonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
